// e2e: clicking the per-card download button should call
// chrome.downloads.download with the right URL + a generated filename.
//
// We don't want the test to actually drop files into the runner's
// Downloads folder, so launchExtension() is asked to stub
// chrome.downloads.download — every call gets recorded to
// window.__IH_DOWNLOAD_CALLS__ and is read back via readDownloadCalls().
import { test, expect } from '@playwright/test';
import {
  launchExtension,
  openSidepanelWithImages,
  readDownloadCalls,
  startFixtureServer,
  type FixtureServer,
  type LaunchedExtension,
} from './_helpers/launchExtension';

let ext: LaunchedExtension;
let fixtureServer: FixtureServer;

test.beforeAll(async () => {
  fixtureServer = await startFixtureServer();
  ext = await launchExtension();
});

test.afterAll(async () => {
  await ext?.context.close();
  await fixtureServer?.close();
});

test('clicking a card download button calls chrome.downloads.download once', async () => {
  const { sidepanel } = await openSidepanelWithImages(ext.context, fixtureServer, ext.extensionId, {
    stubDownloads: true,
  });

  // Sanity: stub installed and starts empty.
  expect(await readDownloadCalls(sidepanel)).toHaveLength(0);

  // Click the first card's per-card download button (.btn-dl). Cards in
  // the grid are virtualized for large lists but the fixture only has 6
  // images so they're all in the DOM.
  const firstDl = sidepanel.locator('#image-grid .image-card .btn-dl').first();
  await firstDl.click();

  // chrome.downloads.download is async — wait for the call to land.
  await expect.poll(() => readDownloadCalls(sidepanel).then((c) => c.length)).toBe(1);

  const calls = await readDownloadCalls(sidepanel);
  expect(calls[0].url).toBeTruthy();
  // Fixture cards include data: URLs (inline SVG) and http(s) URLs
  // (background-image fixtures). Either is a valid download source for
  // chrome.downloads.download — only require non-empty + scheme-like.
  expect(calls[0].url).toMatch(/^(https?|data):/);
  // Filename is generated by sidepanel/utils.ts > generateFilename.
  // It at least has a real extension and no path separators.
  expect(calls[0].filename).toBeTruthy();
  expect(calls[0].filename).not.toContain('/');
  expect(calls[0].saveAs).toBe(false);
});

test('clicking three different cards records three distinct download URLs', async () => {
  const { sidepanel } = await openSidepanelWithImages(ext.context, fixtureServer, ext.extensionId, {
    stubDownloads: true,
  });

  const dlButtons = sidepanel.locator('#image-grid .image-card .btn-dl');
  const totalCards = await dlButtons.count();
  // Fixture has 6 cards; we only need 3 distinct.
  expect(totalCards).toBeGreaterThanOrEqual(3);

  await dlButtons.nth(0).click();
  await dlButtons.nth(1).click();
  await dlButtons.nth(2).click();

  await expect.poll(() => readDownloadCalls(sidepanel).then((c) => c.length)).toBe(3);

  const calls = await readDownloadCalls(sidepanel);
  const urls = new Set(calls.map((c) => c.url));
  expect(urls.size).toBe(3);
});
